server:
  port: 9001


# 开启降级 feign.histrix
feign:
  hystrix:
    enabled: true

# Eureka配置
eureka:
  client:
    register-with-eureka: false # 不向Eureka注册自己
    service-url:
      #多个eureka service集群之间用逗号分隔
      defaultZone: http://127.0.0.1:7001/eureka/