server:
  port: 8001

## mybatis配置
#mybatis:
#  type-aliases-package: com.wxuy.example.eureka.pojo
#  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml

# spring配置
spring:
  application:
    name: eureka-provider
#   已经在启动类中配置了跳过jdbc连接的配置  @EnableAutoConfiguration(exclude = {DataSourceAutoConfiguration.class}) //启动的时候跳过jdbc的连接
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/db01?userSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: root

# Eureka的配置,服务注册到哪里
eureka:
  client:
    service-url:
      #多个eureka service集群之间用逗号分隔
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    instance-id: eureka-service-8001 # 修改eureka上的默认描述信息
    prefer-ip-address: true

# info配置
info:
  app.name: example-eureka
  company.name: com.wxuy.example.eureka